ALTER TABLE fornecedores
ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(20),
ADD COLUMN IF NOT EXISTS cidade VARCHAR(120),
ADD COLUMN IF NOT EXISTS observacoes TEXT;

ALTER TABLE fornecedores
DROP COLUMN IF EXISTS contato;
